### ISSUE TITLE
how to add parameters?

### ISSUE THREAD

**Issue by maqinzhang** [wiztools/rest-client#36]
I want to add paramters with the request, but I cannot find how to add the parameters?
I donot want to add the paramters after the request link with "?" or "&" ?

**Comment by maqinzhang** [comment]
I know ! It was careless of me ! This is a good software ! thanks !

**Comment by subwiz** [comment]
Great! For people who visit this issue in future, the [answer is here](http://stackoverflow.com/questions/8582411/how-do-you-send-a-post-using-wiztools-rest-client/21411162#21411162).
