### ISSUE TITLE
Support for loading requests from older versions

### ISSUE THREAD

**Issue by jgabrielygalan** [wiztools/rest-client#38]
We have a lot of sample requests created with an older version of REST client, and we cannot open them with 3.5. It would be great to have backward compatibility or a way to migrate files from the old format to the new one.

**Comment by subwiz** [comment]
I [broke compatibility with 2.x when I released 3.0](http://blog.wiztools.org/2012/09/restclient-30-version-available-for.html). All 3.x files should be openable by 3.5 version.

Unfortunately, I don't have any plan of writing a 2.x migration tool as of now. But, note that the file formats used by RESTClient are plain XML--so it may be possible for you to develop a script to do this. Even more awesome if you could share the script with the community.

**Comment by lenovodev** [comment]
Hi Subash, 

Really useful tool and ease of use. But as of now I am trying to use the threatconnect api with this tool. But we are unable to hit a request even with your tool. 
Can u please help us in this to let us know how to send header request to the api as you would have already used the same.

We have created signature which consist of url and the scretkey with hmac256 for the same and unix timestamp.
Even in your sample code the threatconnect code is missing , if you could help in with the missing code snippet would be real help.

Thanks in advance.
