### ISSUE TITLE
Binaries files on github releases

### ISSUE THREAD

**Issue by EduardoLeggiero** [wiztools/rest-client#41]
Hi,

I am a contributor of the Archlinux operation system and the maintainer of the Wiztools RESTClient (see: https://aur.archlinux.org/packages/restclient/).
At this moment I forked your repository only to add the binaries on the github release.

Could you, please, add the binaries (for the ui and cli) on your releases?
Like on my fork: https://github.com/EduardoLeggiero/rest-client/releases/tag/restclient-3.5
At this way, I can use only your official repository to get the binaries to make the Archlinux package.

PS: The FossHub website protect the files against automated download by using referer headers and redirects and can't be used by the archlinux build system.

Thank you,

Eduardo Leggiero

**Comment by subwiz** [comment]
Done: https://github.com/wiztools/rest-client/releases/tag/restclient-3.5

**Comment by subwiz** [comment]
In future releases, I will ensure that I release the binaries via GitHub too.
