### ISSUE TITLE
GET 10 MB Chunked Transfer Not Allowing Download of Body

### ISSUE THREAD

**Issue by melloware** [wiztools/rest-client#42]
Using version 3.5 on Java 8.

We have a HTTP GET service which returns a ZIP file payload.  Your client works when the payload is roughly 2MB and we are able to get the result and download it.  If the files is 11MB though your tool just displays the Body as blank.   You should have some way of signaling the payload is too large on the Body display and giving a way of downloading it.  Here is the headers of our returned result.

Server  Apache-Coyote/1.1
Pragma  No-cache
Cache-Control   no-cache
Expires Wed, 31 Dec 1969 19:00:00 EST
Set-Cookie  JSESSIONID=PHihH7crw0SuDnQOqIWB0RWt; Path=/afcatc; HttpOnly
content-disposition attachment;filename=AFCATC-input-files.zip;charset=UTF-8
Content-Type    _/_
Transfer-Encoding   chunked
Date    Wed, 16 Dec 2015 13:26:28 GMT

**Comment by subwiz** [comment]
Good idea. Let me check the possibility.

**Comment by melloware** [comment]
Excellent thanks for looking into it.  Great little tool by the way!
