### ISSUE TITLE
WebDAV COPY, MOVE and LOCK commands should be added

### ISSUE THREAD

**Issue by MovGP0** [wiztools/rest-client#46]
`COPY`, `MOVE`, `LOCK`, `UNLOCK`, `PROPWATCH`, and `MKCOL` are part of the [WebDAV](https://tools.ietf.org/html/rfc2518) protocol and can also be used for REST APIs. The commands should therefore be added. 

There are even more [WebDAV methods](https://msdn.microsoft.com/en-us/library/aa142917(v=exchg.65).aspx). Instead of adding them, it might be useful to let the user type in a method that is not available.

**Comment by subwiz** [comment]
> it might be useful to let the user type in a method that is not available.

Let me check this possibility. It will also make the tool extensible.

**Comment by subwiz** [comment]
Can now be done using custom methods.
