### ISSUE TITLE
Status bar

### ISSUE THREAD

**Issue by cih997** [wiztools/rest-client#55]
Hi,

I'm using RESTClient 3.6 (restclient-ui-fat-3.6.jar). After request is completed I can see the Response time and size in the status bar (bottom). Unfortunately after a short while the status bar changes to "WizTools.org RESTClient" and in most cases I cannot even note the request time.

This is annoying especially when the request time is crucial for me.

Thanks
K

**Comment by subwiz** [comment]
I have a 20 second timeout to change _WizTools.org RESTClient_. Will changing this to 40 help you?

**Comment by cih997** [comment]
Hi @subwiz,

I think one minute is a minimum, especially I cannot click / select and copy the time value and sometimes I need to write it down somewhere. 60 seconds should be okay.

Also, you may consider adding right click -> copy to clipboard action for status bar. That would help in my opinion.

Thanks
Krzysztof
