### ISSUE TITLE
Doesn't work with Java v10.0.1

### ISSUE THREAD

**Issue by symonsoft** [wiztools/rest-client#70]
Shows up splash screen and immediately exits.

    c:\>java -version
    java version "10.0.1" 2018-04-17
    Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
    Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

**Comment by subwiz** [comment]
Sometime back I updated the master branch to make the build compatible with Java 10. If you need, I can give you a build for your OS. Which OS do you use?

I'll do a Java 10 supported release soon.

**Comment by symonsoft** [comment]
Super! I'll wait for release.

**Comment by subwiz** [comment]
Release [done](https://github.com/wiztools/rest-client/releases/tag/3.6.2).
