### ISSUE TITLE
Make the key-value editor of the Body tab to read the current values

### ISSUE THREAD

**Issue by negora** [wiztools/rest-client#72]
Dear team of Wiztools:

Right now, when you invoke the key-value editor in the `Body` tab (using the `Insert parameters` button), it asks you to erase the body: 

> Body text exists. Erase?

Wouldn't it be much more useful if it parsed the current values from the body, instead of erasing them? Editing the parameters directly in `application/x-www-form-urlencoded` format is complicated. Specially because the editor hasn't got an option to wrap words dinamically.

Thank you.

**Comment by subwiz** [comment]
Have you checked the *Multi-insert* option?

<img width="518" alt="rc" src="https://user-images.githubusercontent.com/140510/44275510-87953f00-a262-11e8-98f0-4f12980cf053.png">

**Comment by negora** [comment]
Thank you a lot @subwiz . I'm looking forward to test the next release ;) .
